# Generated by Django 4.2.19 on 2025-03-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
    ]
