# Generated by Django 4.2.19 on 2025-03-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_compra_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': [('es_admin', 'Puede ver ventas'), ('es_comprador', 'Puede ver solo sus compras')]},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('es_admin', 'Puede gestionar productos'), ('es_comprador', 'Puede comprar productos')]},
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='Producto',
            new_name='producto',
        ),
    ]
