# Generated by Django 4.2.19 on 2025-03-02 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0006_alter_compra_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': [('ver_compra', 'Puede ver compra'), ('agregar_compra', 'Puede agregar compra')]},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('ver_producto', 'Puede ver producto'), ('agregar_producto', 'Puede agregar producto'), ('cambiar_producto', 'Puede cambiar producto')]},
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
